---
abstract: 'DAIA Server as Plack application'
author:
  - 'Jakob Voss'
build_requires:
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-DAIA
requires:
  CGI: 0
  DAIA: 0.4
  Encode: 0
  JSON: 0
  LWP::Simple: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
  XML::LibXML: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/Plack-App-DAIA/issues
  repository: https://github.com/nichtich/Plack-App-DAIA
version: 0.4
