---
abstract: 'DAIA Server as Plack application'
author:
  - 'Jakob Voß'
build_requires:
  Test::Builder::Tester: 0
  Test::Warn: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-DAIA
requires:
  CGI: 0
  Carp: 0
  DAIA: 0.41
  Encode: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::Simple: 0
  Plack::Component: 0
  Plack::Middleware::Static: 0
  Plack::Request: 0
  Plack::Test: 0
  Plack::Util::Accessor: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Test::Builder::Module: 0
  Test::JSON::Entails: 0
  Test::More: 0
  Try::Tiny: 0
  URI::Escape: 0
  base: 0
  parent: 0
  perl: v5.10.1
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/Plack-App-DAIA/issues
  homepage: https://github.com/nichtich/Plack-App-DAIA
  repository: https://github.com/nichtich/Plack-App-DAIA.git
version: 0.52
